global:
  sql_adapter: default

local:
  vhost: "https://localhost"
  wordpress_path: "/var/www/html/"
  database:
    name: "<%= ENV['MYSQL_DATABASE'] %>"
    user: "<%= ENV['MYSQL_USER'] %>"
    password: "<%= ENV['MYSQL_PASSWORD'] %>"
    host: "<%= ENV['LOCAL_DB_HOST'] %>"

production:
  vhost: "<%= ENV['PRODUCTION_URL'] %>"
  wordpress_path: "<%= ENV['PRODUCTION_DIR_PATH'] %>"

  database:
    name: "<%= ENV['PRODUCTION_DB_NAME'] %>"
    user: "<%= ENV['PRODUCTION_DB_USER'] %>"
    password: "<%= ENV['PRODUCTION_DB_PASSWORD'] %>"
    host: "<%= ENV['PRODUCTION_DB_HOST'] %>"
    port: "<%= ENV['PRODUCTION_DB_PORT'] %>"

  exclude:
    - '.git/'
    - '.gitignore'
    - '.gitmodules'
    - '.env'
    - 'node_modules/'
    - 'bin/'
    - 'tmp/*'
    - 'Gemfile*'
    - 'Movefile'
    - 'movefile'
    - 'movefile.yml'
    - 'movefile.yaml'
    - 'wp-config.php'
    - 'wp-content/*.sql.gz'
    - '*.orig'
    - "wp-content/uploads/backwpup*/*"
    - ".htaccess"

  ftp:
    host: "<%= ENV['PRODUCTION_FTP_HOST'] %>"
    user: "<%= ENV['PRODUCTION_FTP_USER'] %>"
    password: "<%= ENV['PRODUCTION_FTP_PASSWORD'] %>"
    passive: true
    scheme: "ftps"
